#import "ourchat/lib.typ" as oc
#import oc.themes: qqnt

#set page(width: auto, height: auto, margin: 0pt, fill: rgb("#1a1a1a"))
#set text(font: ("Noto Sans SC", "DejaVu Sans"), size: 13pt, fill: white)

#let data = json(sys.inputs.at("json", default: "./example.json"))

#let anon = qqnt.user(
  name: [匿名用户],
  avatar: circle(fill: rgb("#555"), text(white)[匿]),
)

#let user = if data.is_anon { anon } else { 
  qqnt.user(
    name: data.name,
    avatar: box(height: 20pt, width: 20pt)[
      #place(center, circle(fill: orange, text(white, 10pt, upper(data.name.at(0)))))
      #place(center, image(data.avatar, width: 100%, height: 100%, fit: "cover"))
    ]
  )
}

#qqnt.chat(
  theme: (
    inherit: "dark",
    background: rgb("#1a1a1a"),
  ),
  width: 320pt,
  
  oc.time[#datetime.today(offset: 8).display("[year]/[month]/[day]")],

  ..data.content.map((item) => {
    if item.type == "text" {
      oc.message(left, user)[
        #item.content
      ]
    } else if item.type == "image" {
      oc.message(left, user)[
        #image(item.content)
      ]
    }
  }),
)

#align(center, {
  text(size: 9pt, fill: rgb("#bababa"))[
    Designed and Generated by OhMyGPA Bot
  ]
  v(10pt)
})